### ISSUE TITLE
Create a WPS script that contains other WPS scripts

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbiswps#111]
Different solutions are possible  : 

-  programmatically with some utilities in a WPS script. Need to write code
- using an encoding file (JSON, XML) that stores the metadata to load the WPSs. The encoding file could be loaded using a WPS script that set the input parameters. 

Comments, ideas are welcome.

**Comment by ebocher** [comment]
@nicolas-f , @SPalominos , @gpetit , @j3r3m1 , @nahtanojoal

**Comment by ebocher** [comment]
Check http://www.bpmn.org/

**Comment by SPalominos** [comment]
Now linked to the process chaining : #8
