### ISSUE TITLE
Declare WPS script as an OSGI bundle

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbiswps#17]
This issue is to start a debate about OSGI and WPS script..

An example here : 
https://github.com/groovy/groovy-core/tree/master/src/examples/osgi/hello-groovy-bundle/org/codehaus/groovy/osgi

**Comment by SPalominos** [comment]
In the example you gave, the script need to have an activator class to be loaded by OSGI. So at least you need 3 files, the activator, the build.xml and the script.

Comparing to the actual solution (the script bundle), there is the same among of files needed and the mechanism used are the same.
