### ISSUE TITLE
Scripts Translation

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbiswps#6]
(Comment from @ebocher) Implements a system based on groovy annotation to set the translation of in-line string like 
``` java
@Process()
def processing() {

literalDataOutput = tr("Process done")
}

@tr(description = ["Process done", ["Process done.","en",
                "Traitement réalisé.","fr"]])
```
Explain in the wiki how to build a script plugin and how to translate the scripts.
(old issue : orbisgis/orbisgis#1088)

**Comment by ebocher** [comment]
@SPalominos  It's done ?

**Comment by SPalominos** [comment]
Not yet, some little fixes on orbisWPS are needed and then the Mapuce_tool and toolbox-editor module should be updated.
