### ISSUE TITLE
DescribeProcess without xml:lang fails while standard says it is optional

### ISSUE THREAD

**Issue by pteigen** [orbisgis/orbiswps#87]
Referring to the standard here:
http://docs.opengeospatial.org/is/14-065/14-065.html#55

The standard says xml:lang is optional and the example query from the standard fails as it does not have xml:lang defined.

When performing a DescribeProcess request without "xml:lang" it fails on an exception in the method:
ProcessTranslator.getTranslatedProcess since "requestedLanguage" is null

--
Petter Teigen

**Comment by ebocher** [comment]
Thanks we will fix it.

**Comment by ebocher** [comment]
Fixed on the 5.1-dev by @SPalominos

**Comment by pteigen** [comment]
Yes. Thank you!
