### ISSUE TITLE
ProgressMonitor::endOfProgress() sets progress < 1 when process finished and stepCount > 1

### ISSUE THREAD

**Issue by pteigen** [orbisgis/orbiswps#89]
Hi

As far as I understand how this class (ProgressMonitor) works I believe that there is a bug.

If stepCount is > 1 (for example 10) then calling progressTo(1) will set progressDone to < 1 (10% in the example).

As endOfProgress() is called automatically from ProcessWorker when the job is done I would expect it to set progress to 100%

Is:
`    @Override
    public void endOfProgress() {
        progressTo(1);
    }`
Should be:
`    @Override
    public void endOfProgress() {
        progressTo(stepCount);
    }`

--
Petter Teigen

**Comment by ebocher** [comment]
Feel free to submit a PR

**Comment by pteigen** [comment]
Thanks. Will do that tomorrow
